-- MySQL Script generated by MySQL Workbench
-- Mon May  7 12:20:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema question
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema question
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `question` DEFAULT CHARACTER SET utf8 ;
USE `question` ;

-- -----------------------------------------------------
-- Table `question`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `question`.`data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `question` VARCHAR(100) NULL,
  `answer` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iddata_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
